### PR TITLE
:recycle: restore the `$auto` in cargo-deb dependencies

### LINKED ISSUE #1793: Install Wayland DEB on Debian 12 error libwx_gtk3u_html-3.0.so.0
Just download latest version Espanso Wayland Debian v.2.2.1 from Github, and got error 

1. Download from Githut using espanso-debian-wayland-amd64.deb
2. sudo apt install ./espanso-debian-wayland-amd64.deb
3. call espanso from console
4. Got this error: 

```
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

- OS: Debian 12
- Version: v2.2.1 (latest version)

## Momentary fix

As devs continue to work on this, [this comment](https://github.com/espanso/espanso/issues/1793#issuecomment-1919055522) fixes the problem for the time being.

### PR DESCRIPTION
**Pull request by AucaCoyan**
This is related to #1849 and also maybe fixes #1793
with `$auto` in the dependencies

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I'm unable to test this as I don't have a Debian machine this week, can somebody try this and see if the #1793 keeps bugging us?
I need to test every scenario:
- Wayland
- X11
- and some wlroots compositor like sway or hyperland
🙏

**Comment by smeech** [comment]
All working well in Linux Mint 22 Xfce (X11) and Ubuntu 24 (Wayland/Mutter).

**Comment by AucaCoyan** [comment]
Yeeeeeeeeah! Only pending to confirm in hyperland or sway 🙌

**Comment by smeech** [comment]
I'm encountering too many hurdles trying to install Hyprland on openSUSE.
I'll have a look at Sway.

**Comment by smeech** [comment]
In Ubuntu + Sway I get `Task "build-binary" not found.`.
Odd, because compilation in the same VM (prior to rollback) worked fine.

**Comment by smeech** [comment]
> I'll have a look at Sway.

Compilation in Ubuntu 24 + Sway is fine.
A real pain because I had to type in all the commands by hand, as I couldn't paste into the VM running Sway!

No progress with Hyprland, I'm afraid. It's just too difficult to get Hyprland working.

**Comment by AucaCoyan** [comment]
at least is one done!
Thanks smeech 🥰

**Comment by AucaCoyan** [comment]
This pr is ready to merge, but I will fix this CI issue [here](https://github.com/espanso/espanso/actions/runs/12224942119/job/34098330635)

**Comment by AucaCoyan** [comment]
fixed in #2176 !
merging this

**Pull request merged**
