### PR TITLE
feat: add devcontainer

### PR DESCRIPTION
**Pull request by phorcys420**
[Discord discussion](https://discord.com/channels/884163483409731584/1013902234469269554/1208736732778864661)
(cc: @AucaCoyan)

---

[Devcontainers](https://containers.dev/) are an open specification for enriching containers with development specific content and settings that allows developers to use containers as developer environments.

This helps with quick setup of development environments in VSCode, GitHub Codespaces, [Coder](https://coder.com) and others.

This PR is the beginning of the inclusion of dev containers in Espanso.
My long-term vision on this is the following :
- [ ] Pre-build the devcontainer image and host it on GHCR to avoid build time overhead (first time only)
- [ ] Cache build dependencies within the image
- [ ] Reuse the devcontainer spec within CI to avoid redundancy
   - see https://github.com/devcontainers/ci
- [ ] Implement cross-compilation to speed up multi-OS testing
   - see https://rust-lang.github.io/rustup/cross-compilation.html

Now these will come in separate PRs, I think this current version is fine to get the idea started.

### CODE REVIEW

**Comment by federico-terzi** [comment]
Hey folks :)

I'm a big fan of devcontainers, but how can they help with Espanso? The software relies on desktop native APIs that AFAIK are not available from inside a devcontainer context. I understand being able to run unit tests from Docker, which makes sense and we are partially doing it already, but you wouldn't be able to run Espanso itself inside (as far as I can think), so what would be the advantage of running the Espanso dev environment within a devcontainer? :)

**Comment by phorcys420** [comment]
> Hey folks :)
> 
> I'm a big fan of devcontainers, but how can they help with Espanso? The software relies on desktop native APIs that AFAIK are not available from inside a devcontainer context.

Hey! Actually, they should be.
I've been writing my PRs for Espanso from within a custom container (see [uwu/basic-env](https://github.com/uwu/basic-env) that has a desktop environment running with noVNC to access it.

We can replicate this setup by using the [`desktop-lite`](https://github.com/devcontainers/features/tree/main/src/desktop-lite) devcontainer feature, I just didn't think of it!

> what would be the advantage of running the Espanso dev environment within a devcontainer? :)

Even without access to a desktop environment, the advantages are as follows :
- Hands-off setup (all the tools install themselves)
- Standardized dev environments to reduce the "works on my machine" phenomenon
- Ability to compile espanso easily
- (Reusable configuration files for CI usage)

Even if you didn't run espanso from within the devcontainer (which you theoretically could, but I'll expand down below), you could still use it as a reference "compilation machine" that you don't have to setup/maintain yourself, which I think is pretty useful (even more when cross-compilation gets there).

I had this other idea that would also make more sense within a devcontainer, I think it'd be great if you could use espanso only with the CLI.
Let me explain, when I was writing my [PowerShell Core PR](https://github.com/espanso/espanso/pull/1824), I needed to have a desktop environment to test my espanso trigger, when in reality, that wasn't useful since I wasn't changing any core espanso behavior, only implementing some "backend logic". (where typing is the front-end)
instead of typing ":test" every now and then, I could've ran `espanso trigger ":test"` and grabbed the output from there for my testing, making the need for a DE gone while still maintaining good testing.

Obviously, when sending a PR you would test it in a "real" environment, but this would really help with debugging !

**Comment by federico-terzi** [comment]
Thanks for sharing! Interesting

**Comment by AucaCoyan** [comment]
Hello! Where are we in this PR? 😄

**Comment by phorcys420** [comment]
hey! I don't know why I left it as a draft actually!
I was just waiting for input and kind of forgot about this PR to be honest.

I'll look into adding the [`desktop-lite`](https://github.com/devcontainers/features/tree/main/src/desktop-lite) feature and undraft this PR :-)

**Comment by AucaCoyan** [comment]
No worries, I'll happily merge this when ready!

**Comment by phorcys420** [comment]
Here it is with the desktop-lite feature!

https://github.com/espanso/espanso/assets/57866459/d1ec9f39-c46b-4128-a864-fce40209bac8

---

In this preview I started espanso from within the VNC sessions's terminal, but you can also run `espanso start` from VSCode and it'll work just as well!

This could definitely be better in the following ways :
- Automatically start espanso whenever built (hot-reload) (needs to be implemented outside of the devcontainer first)
- Automatically start the text editor

I also think `espanso start` should have a `--no-detach` flag or whatever to be able to CTRL+C the espanso process whenever you don't need it anymore and to have `espansod` logs directly, I think that would enhance the developer experience.

I can submit issues for those if needed :-)

**Comment by phorcys420** [comment]
@AucaCoyan @federico-terzi the PR is ready to be merged if you don't see anything else to add :-)

**Comment by AucaCoyan** [comment]
WOW that is amazing!
I'm very sorry I took so much to respond, I initially thought that I needed to test the devcontainer in my pc first. With the video it was more than enough!
All good!
If you are willing, we could improve the `CONTRIBUTING.md` docs, but that is another PR 😄

**Review by AucaCoyan — APPROVED** [review]
I love this!

**Comment by phorcys420** [comment]
🚀

**Pull request merged**
