### PR TITLE
Revert PR 1769 (fixes #1826)

### LINKED ISSUE #1793: Install Wayland DEB on Debian 12 error libwx_gtk3u_html-3.0.so.0
Just download latest version Espanso Wayland Debian v.2.2.1 from Github, and got error 

1. Download from Githut using espanso-debian-wayland-amd64.deb
2. sudo apt install ./espanso-debian-wayland-amd64.deb
3. call espanso from console
4. Got this error: 

```
espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory
```

- OS: Debian 12
- Version: v2.2.1 (latest version)

## Momentary fix

As devs continue to work on this, [this comment](https://github.com/espanso/espanso/issues/1793#issuecomment-1919055522) fixes the problem for the time being.

### LINKED ISSUE #1826: Weird tiny, unusable, blocking mid-screen box / popup / widget apparing since espanso upgrade on Ubuntu 22.04.3 / wayland
**Describe the bug**
After upgrading from an older espanso version, on service start a weird graphic box is rendered. On clicking it, some colorful dots are rendered below. (see screenshot).

The start notification popup renders succesfully, though.

No interaction is possible, hence it also blocks my left and top bars.

**To Reproduce**
1. Just start espanso

**Expected behavior**
Espanso should be invisible or render as an icon inside menu bar.

**Screenshots**
grafik

**Logs**
```
 ~/.c/e/config  espanso log                                                                                                                                                                                         Fr 26 Jan 2024 13:32:51 CET
13:31:52 [daemon(3013298)] [INFO] reading configs from: "/home/ben/.config/espanso"
13:31:52 [daemon(3013298)] [INFO] reading packages from: "/home/ben/.config/espanso/match/packages"
13:31:52 [daemon(3013298)] [INFO] using runtime dir: "/home/ben/.cache/espanso"
13:31:52 [daemon(3013298)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-91-generic
13:31:52 [daemon(3013298)] [INFO] watching for changes in path: "/home/ben/.config/espanso"
13:31:52 [daemon(3013298)] [INFO] espanso version: 2.2.1
13:31:52 [daemon(3013298)] [INFO] spawning the worker process...
13:31:52 [daemon(3013298)] [INFO] binded to IPC unix socket: /home/ben/.cache/espanso/espansodaemonv2.sock
13:31:52 [worker(3013305)] [INFO] reading configs from: "/home/ben/.config/espanso"
13:31:52 [worker(3013305)] [INFO] reading packages from: "/home/ben/.config/espanso/match/packages"
13:31:52 [worker(3013305)] [INFO] using runtime dir: "/home/ben/.cache/espanso"
13:31:52 [worker(3013305)] [INFO] system info: Ubuntu v22.04 - kernel: 5.15.0-91-generic
13:31:52 [worker(3013305)] [INFO] using WaylandAppInfoProvider
13:31:52 [worker(3013305)] [INFO] binded to IPC unix socket: /home/ben/.cache/espanso/espansoworkerv2.sock
13:31:52 [worker(3013305)] [INFO] monitoring the status of the daemon process
13:31:52 [worker(3013305)] [INFO] detection module will use this keyboard layout: [R=, M=, L=de, V=, O=]
13:31:52 [worker(3013305)] [INFO] using EVDEVSource
13:31:52 [worker(3013305)] [INFO] Querying modifier status...
13:31:52 [worker(3013305)] [INFO] inject module will use this keyboard layout: [R=, M=, L=de, V=, O=]
13:31:52 [worker(3013305)] [INFO] using EVDEVInjector
13:31:52 [worker(3013305)] [INFO] using WaylandFallbackClipboard
```

**Setup information**
- OS: What OS are you using?: Ubuntu 22.04.3 LTS
- Version: 2.2.1 wayland via .deb

### PR DESCRIPTION
**Pull request by AucaCoyan**
I've been `git bisect`ing and found 2 problems, 
one, the build of the dpkg with the old ubuntu distro (18.04) is messing with modern debian distributions. It installs with gtk3.0 but it has been deprecated in debian 12 (and ubuntu 22.04 I believe). I solved this by writing a manual script to compile a `.deb` file and running manually the script in every bisect.

```bash
#!/bin/bash
set -e
echo "Installing cargo-deb"
cargo install cargo-deb --version 1.44.1

echo "Building Wayland deb package"
cargo deb -p espanso --variant wayland -- --no-default-features --features "modulo wayland vendored-tls"

cp target/debian/espanso-wayland*.deb espanso-debian-wayland-amd64.deb
echo "  Done!"
```
This works allright, except the dependencies written in `espanso/Cargo.toml` aren't quite right, causing installation failures (#1793, #1739, #1662 )
So this led me to write 
```toml
depends = "$auto"
```
on the wayland

These PRs #1697 #1769 are rolled back in this proposal. The problem with the second is that is pointed to Hyperland, a minor desktop enviroment, while Wayland is broken in many PCs. (#1826 )

I don't know how to provide another solution to the issues #1768 and #1750. Maybe updating client-toolkit to their latest version, v0.18.1, we'll see..

this fixes #1793 

## Instructions to try this PR:
checkout the git branch:
```bash
git clone -b revert-PR-1769 https://github.com/AucaCoyan/espanso
cd espanso/
```
install the dependencies:
```bash
cargo install rust-script --version "0.7.0"
cargo install --force cargo-make --version 0.37.5
sudo apt install libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev libwxgtk3.2-dev
```
and then compile the `.dpkg`
```bash
#!/bin/bash
set -e
echo "Installing cargo-deb"
cargo install cargo-deb --version 1.44.1

echo "Building Wayland deb package"
cargo deb -p espanso --variant wayland -- --no-default-features --features "modulo wayland vendored-tls"

cp target/debian/espanso-wayland*.deb espanso-debian-wayland-amd64.deb
echo "  Done!"
```

### CODE REVIEW

**Comment by morgan-dgk** [comment]
fyi, I think this is likely to break espanso on any wl_roots based compositors, not just Hyprland

**Comment by AucaCoyan** [comment]
Oh thanks! I read a lot about wayland yesterday and [found out that is a hot topic in the linux community](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277).
I would like to try and debug the problem, so we can move forward, but currently I use Debian with a pc that has an Nvidia card. Hyprland is out of the park for me. Can you give me a hint of any other wayland compositor that depends on wlroots?

**Comment by morgan-dgk** [comment]
It's certainly seems to be contentious :sweat_smile:. From what I can tell, Sway seems to be reasonably popular.

**Comment by federico-terzi** [comment]
Hey!

> one, the build of the dpkg with the old ubuntu distro (18.04) is messing with modern debian distributions. It installs with gtk3.0 but it has been deprecated in debian 12 (and ubuntu 22.04 I believe).

AFAIK, we should build on the oldest version we are planning to support. If we start building on images using ubuntu 22.04, older distros might break... It's a tricky balance, that's why it's so common to build from sources on Linux

I'm also not sure if putting `$auto` is the right choice, as we moved away from it recently due to different issues: https://github.com/espanso/espanso/pull/1697/files

I don't have a good solution for this, so feel free to continue experimenting. Let's just make sure that we don't break more things than we are trying to fix :)

**Comment by AucaCoyan** [comment]
Yes, we are not ready with this. I would like to fix the hyprland bug, but so far I had no success with my pc.

**Comment by AucaCoyan** [comment]
I couldn't setup my pc to debug hyprland 😢 .
I'm between a rock and a hard place, I don't want to merge this because it will cause the bug in wl_roots, but at the same time if I don't merge it the fix for 1826 isn't going to land.

I'm in need of help, what do you think merging this to a _temporary_ branch and some other contributor try to solve the wl_roots problem? I'm not happy with breaking dev and wait for somebody else to fix it.
👂🏼 I'm listening to options here 👂🏼

**Comment by morgan-dgk** [comment]
> I couldn't setup my pc to debug hyprland 😢 . I'm between a rock and a hard place, I don't want to merge this because it will cause the bug in wl_roots, but at the same time if I don't merge it the fix for 1826 isn't going to land.
> 
> I'm in need of help, what do you think merging this to a _temporary_ branch and some other contributor try to solve the wl_roots problem? I'm not happy with breaking dev and wait for somebody else to fix it. 👂🏼 I'm listening to options here 👂🏼

#1891 should fix this :slightly_smiling_face:

**Comment by AucaCoyan** [comment]
Excellent! Thank you for your help!

**Comment by morgan-dgk** [comment]
can we close this @AucaCoyan or are there still changes we need here?

**Comment by AucaCoyan** [comment]
Yes! I double checked the debian build script is ok, but that can be discussed in another issue.
Closing!

**Pull request closed without merging**
