### PR TITLE
Create a rpm build automatically

### PR DESCRIPTION
**Pull request by bekoeppel**
I extended the Github build pipeline to also create a RPM build (for Fedora). Note:
  * Currently only creates the wayland build
  * I don't know how to test the github pipelines unfortunately

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I love it! This is one of the most wanted thing we are reading from users ❤️

**Comment by AucaCoyan** [comment]
Hi! Sorry for the delay. Let me fix the CI in the dev branch so you can merge and we'll continue from there

**Comment by smeech** [comment]
#1948, #1208

**Comment by AucaCoyan** [comment]
Hi! I'm sorry for not bringing the news before... `dev` CI is all green!
Can you update your branch and push it again?

**Comment by bekoeppel** [comment]
Done

**Comment by AucaCoyan** [comment]
Yup! All green. Thank you! Merging!

**Pull request merged**
