### PR TITLE
Show regex in search bar

### LINKED ISSUE #773: Show regex triggers in search bar
As described [here](https://github.com/federico-terzi/espanso/issues/762#issuecomment-939360857), it would be nice to have regex triggers displayed on the search bar

image

### PR DESCRIPTION
**Pull request by ghost**
Resolve #773 

image

There is a past comment about a concern with long regular expressions. However, there is already a visual overflow in search windows  when the `trigger` or `replace` contains long strings without spaces. I believe this should be resolved separately.

### CODE REVIEW

**Comment by AucaCoyan** [comment]
Wow nice! It already shows promising
Make sure we have a green CI and we are good to go 🏎️

**Comment by ghost** [comment]
@AucaCoyan The failures don't seem to be caused by my change, and they are from different files.

**Comment by AucaCoyan** [comment]
I fixed the errors in #2002, can you pull the latest changes?

**Comment by ghost** [comment]
Thanks, it's been done.

**Comment by AucaCoyan** [comment]
Thank you! Let's goooooo!

**Pull request merged**
