### PR TITLE
Add option to open config folder to context menu

### PR DESCRIPTION
**Pull request by BNolet**
* Added menu option to open config folder
* What is considered the "config" folder here is the espanso folder as per the existing paths variable in espanso.

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I didn't realize it needs my approval to run the workflow 😋

**Comment by BNolet** [comment]
lol the only one that worked was the one I was able to test 😅

**Comment by AucaCoyan** [comment]
The other ones failed because of formatting, so with `cargo fmt` and git push it solves all the red crosses (this time). An easy fix!

**Comment by AucaCoyan** [comment]
After we resolved the #1878 , I think this is ready for merge. Is that right? 🛩️

**Comment by BNolet** [comment]
This should be ready to go yeah :D

**Comment by AucaCoyan** [comment]
Thank you!

**Comment by federico-terzi** [comment]
Happy to see new features being added! :)

**Pull request merged**
