### PR TITLE
Include a Search Bar shortcut configuration section in the default config file

### PR DESCRIPTION
**Pull request by olitreadwell**
Include a Search Bar shortcut configuration section in the default config file

### CODE REVIEW

**Comment by smeech** [comment]
I think that's useful, especially as most Linux users will need to reconfigure the default _away_ from ALT+SPACE.

Is this an opportunity to add a [`# search_trigger:`](https://espanso.org/docs/configuration/options/#customizing-the-search-trigger) too? I would favour `#search#` rather than that suggested in the docs, and would be happy to change them accordingly.

**Comment by AucaCoyan** [comment]
I'm fine with adding this comments in the `default.yml`
What do you think @smeech ?

**Review by AucaCoyan — APPROVED** [review]

**Comment by smeech** [comment]
> I'm fine with adding this comments in the `default.yml` What do you think @smeech ?

Yes, good idea. See my comments above.

**Comment by AucaCoyan** [comment]
Great! @olitreadwell can you do us a favour and add the requested changes? 🙏🏼 
Thank you!

**Review by smeech — COMMENTED** [review]
Reviewed.

**Comment by olitreadwell** [comment]
Thanks!

I will get back to this later this week and update the pull request with the requested changes.

**Pull request merged**
