### PR TITLE
Add label to espanso cli on match

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Review by AucaCoyan — APPROVED** [review]

**Review by federico-terzi — COMMENTED** [review]
Hey @kud, thanks for the contribution!

Before proceeding, we should pull from `dev` to get the latest CI fixes and make sure everything is running properly. When you get the chance, could you please pull from `dev` and push? :)

PS: sorry for the late reply!

**Comment by kud** [comment]
Sure thing, thanks!

**Comment by kud** [comment]
It's done @federico-terzi 😌

**Comment by federico-terzi** [comment]
@kud Thanks! It seems the formatting is off, could you try running `cargo fmt` on the file you changed? :)

**Comment by kud** [comment]
`zsh: command not found: cargo`

I think I need your help on this one please :D

**Comment by federico-terzi** [comment]
@AucaCoyan Do you think you can help @kud with formatting? :) If not, no worries, I can look at it this weekend

**Comment by kud** [comment]
I will try to install cargo at first and see how it goes 😌

**Comment by AucaCoyan** [comment]
Sure! @kud hit me up in discord or an email if you want some help!
https://discord.gg/DFcCNDg7bB or aucacoyan@gmail.com

**Comment by federico-terzi** [comment]
Thanks folks! Fixed the formatting issue :)

**Comment by kud** [comment]
lovely, thanks!

My first PR 😊

**Comment by AucaCoyan** [comment]
> first PR

First of many I hope ! ❤️

**Comment by kud** [comment]
@federico-terzi @AucaCoyan 

I don't understand I still have an error.

```
  - trigger: "??r.okletsgo"
    replace: "https://www.youtube.com/watch?v=AWM5ZNdWlqw"
    label: "Okay Let's Go"
```

generates

```
??r.okletsgo - Okay Let's Go - Okay Let's Go
```

via `espanso match list`

**Pull request merged**
