### PR TITLE
feat/update wayland modifier sync

### LINKED ISSUE #1776: [espanso-detect] Espanso Sync Tool window not rendering correctly on wayland
**Describe the bug**
The window created by espanso-detect fails to render correctly on Wayland. The window is created but the Espanso logo and text is not shown. Instead, the window is filled with a rainbow gradient. 

**To Reproduce**
1. Run espanso worker or espanso service start

**Expected behavior**
The espanso sync tool window should display the logo and text correctly. 

**Screenshots**

image

**Logs**
Relevant logs are from Wayland compositor. 

```
[3375819.298] wl_callback@3.done(89687)
[3375819.312]  -> wl_registry@2.bind(9, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@3)
[3375819.340]  -> zwp_primary_selection_device_manager_v1@3.get_device(new id zwp_primary_selection_device_v1@14, wl_seat@8)
[3375819.380]  -> wl_compositor@5.create_surface(new id wl_surface@15)
[3375819.395]  -> wl_registry@2.bind(13, "xdg_wm_base", 2, new id [unknown]@16)
[3375819.437]  -> wl_shm@4.create_pool(new id wl_shm_pool@17, fd 20, 4096)
[3375819.477]  -> xdg_wm_base@16.get_xdg_surface(new id xdg_surface@18, wl_surface@15)
[3375819.490]  -> xdg_surface@18.get_toplevel(new id xdg_toplevel@19)
[3375819.499]  -> wl_surface@15.commit()
[3375819.511]  -> xdg_toplevel@19.set_min_size(2, 1)
[3375819.519]  -> xdg_surface@18.set_window_geometry(0, 0, 1, 1)
[3375819.530]  -> wl_compositor@5.create_surface(new id wl_surface@20)
[3375819.539]  -> wl_seat@8.get_pointer(new id wl_pointer@21)
[3375819.554]  -> zxdg_decoration_manager_v1@9.get_toplevel_decoration(new id zxdg_toplevel_decoration_v1@22, xdg_toplevel@19)
[3375819.568]  -> xdg_toplevel@19.set_title("Espanso Sync Tool")
[3375819.587]  -> wl_shm@4.create_pool(new id wl_shm_pool@23, fd 22, 4096)
[3375819.605]  -> wl_seat@8.get_keyboard(new id wl_keyboard@24)

```

**Setup information**
- OS: Arch Linux 6.6.4 / Hyprland v.0.33.1
- Version:  2.2.0 built from source with latest fix for sctk from dev branch.

### PR DESCRIPTION
**Pull request by morgan-dgk**
This should fix #1776, #1826 and #1843. I have done some limited testing locally and espanso appears to function normally.  

This PR updates the sctk dependency to the latest version and removes the "Espanso Sync Tool" window entirely as it is not necessary to get keyboard modifier status from the display server. 

Apologies for the included merge commit, I am a bit of a git rookie.

### CODE REVIEW

**Comment by AucaCoyan** [comment]
that last one `;` 😆 
happens to us all!

**Comment by AucaCoyan** [comment]
Thank you for the effort! This looks promising ❤️ 
And don't worry for the commits here, we normally squash pull requests so it's easier to roll back if something goes wrong

**Comment by morgan-dgk** [comment]
Apologies, after some further testing this requires more work. The modifier state is not correctly updating in some cases.

**Comment by AucaCoyan** [comment]
That's still some improvement! We are close to the finish line

**Comment by AucaCoyan** [comment]
superseded by #1901

**Pull request closed without merging**
