### PR TITLE
chore: add github issue form bug and feat templates

### PR DESCRIPTION
**Pull request by tobiasbueschel**
GitHub has added issue form support for public repositories (see [docs here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)), which can help to gather more structured information when bugs or feature request issues are created.

This PR converts the previous bug and feature request to use issue forms.

**Here's an example from Docusaurus: https://github.com/facebook/docusaurus/issues/new/choose**

image

Please note: this can only be tested once it has been merged to `master`.

### CODE REVIEW

**Comment by tobiasbueschel** [comment]
@AucaCoyan sure, I've switched the target branch to be `dev`! Cheers :)

**Comment by AucaCoyan** [comment]
I would go green light if it was for me!
Let me check with Federico because he is the admin and has everything in mind 🙆🏼‍♂️

**Comment by AucaCoyan** [comment]
I searched how to auto-tag issues from creation and saw that you did put the line:
```yaml
labels: [bug, 'status: needs triage']
```
That is so useful for triaging! Thanks!
Now I _really_ want to land this PR 👏🏼

**Review by AucaCoyan — APPROVED** [review]
This is really useful for triage users, it adds `needs triage` to easily know when an issue is still evolving its requirements or reproduction cases

**Comment by AucaCoyan** [comment]
Hi Tobias! We had a meeting last Wednesday and we decided to go forward with issues and deprecate discussions. This means this PR is getting merged!
I have a couple of comments to add up:
- can you add the discord server? the link is https://discord.gg/DFcCNDg7bB
- I think it's better not to have required fields everywhere, maybe one per issue type, sometimes I'm personally a bit lazy to complete all the fields, and I think other people might if they want to ask for a simple question, or report a bug that they don't know how of if it is in order. Do you think the templates can be simplified?

**Comment by tobiasbueschel** [comment]
> Hi Tobias! We had a meeting last Wednesday and we decided to go forward with issues and deprecate discussions. This means this PR is getting merged! I have a couple of comments to add up:
> 
> * can you add the discord server? the link is [discord.gg/DFcCNDg7bB](https://discord.gg/DFcCNDg7bB)
> * I think it's better not to have required fields everywhere, maybe one per issue type, sometimes I'm personally a bit lazy to complete all the fields, and I think other people might if they want to ask for a simple question, or report a bug that they don't know how of if it is in order. Do you think the templates can be simplified?

Hi @AucaCoyan,

That's great news :) I've added the Discord channel and have removed most of the required fields in both the bug and feature templates apart from one as per your suggestion.

We could further simplify the fields in each issue template, but some of them are helpful such as e.g., `Your environment`, or `Logs` to help troubleshoot issues. What do you think?

Also, GitHub YAML issue forms supports default assignees and a few other options detailed here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax.

Let me know if there's anything else I should add / change?

**Comment by AucaCoyan** [comment]
Thank you! I think we are good as we are now. We can tweak it after we start using it and see where it needs improvement. If you are okay with it, change the PR to `Ready for review` and I'll merge it! 😄

**Review by AucaCoyan — APPROVED** [review]
all good!

**Comment by tobiasbueschel** [comment]
Thanks @AucaCoyan I've marked it as ready for review!

**Pull request merged**
