### PR TITLE
Debug windows

### PR DESCRIPTION
**Pull request by n8henrie**

### CODE REVIEW

**Comment by AucaCoyan** [comment]
I saw this issue once in the #1877 PR, it was caused by CC in another file, maybe if we put
```toml
[workspace.dependencies]
cc = "=1.0.73"
```
does it work? `cc` is really weird sometimes
The discussion in discord is linked in the PR if you are willing to depth into the details.

**Comment by n8henrie** [comment]
@AucaCoyan No luck ¯\\\_(ツ)_/¯

**Comment by n8henrie** [comment]
Oh, I apologize -- I thought this was on my fork (n8henrie/espanso) -- didn't mean to push debug stuff here.

**Comment by AucaCoyan** [comment]
no worries! it's there so we can use it 😄

**Pull request closed without merging**
